development:
  adapter: postgresql
  url: postgres://localhost/teddies_shop_development

test:
  adapter: postgresql
  url: postgres://localhost/teddies_shop_test

production:
  adapter: postgresql
  url: postgres://localhost/teddies_shop_production
